tutorial/accounts/urls.py
from django.conf.urls import url
from django.conf import settings
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView
from . import views


app_name = 'accounts'

urlpatterns = [
url(r'^signup/$', views.signup, name='signup'),
url(r'login/$', views.login, name='login'),
# path('login/', auth_views.LoginView.as_view(template_name='accounts/login_form.html'), name='login'),
path('logout/', auth_views.LogoutView.as_view(), name='logout'),
# url(r'^login/$', auth_views.auth_login, name='login',kwargs={'template_name':'accounts/login_form.html'}),
# url(r'^logout/$', auth_views.auth_logout, name='logout',kwargs={'next_page':settings.LOGIN_URL}),
url(r'^profile/$', views.profile, name='profile'),
]

tutorial/blog/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv
app_name = 'blog'


urlpatterns = [
    url(r'^$', views_cbv.post_list, name='post_list'),
    url(r'^(?P<pk>\d+)/$', views_cbv.post_detail, name='post_detail'),

    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),

    url(r'^cbv/new/$', views_cbv.post_new),
    url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit),
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete),
    

    # url(r'^$', views.post_list, name='post_list'),
    # url(r'^(?P<id>\d+)/$', views.post_detail, name='post_detail'),
]

tutorial/tutorial/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path

# def root(request):
#     return redirect('blog:post_list')

urlpatterns = [
    # url(r'^$',root, name='root'), 아래 lambda 함수를 써서 하는걸 더 많이 씀 
    url(r'^$', lambda r: redirect('blog:post_list'), name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#settings.MEDIA_URL로 설정을 한다면 document_root=settings.MEDIA_ROOT 에서 파일을 찾아서 서빙을 하겠다
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

tutorial/tutorial/templates/layout.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0,maximum-scale=1.0, user-scalable=no" />
    <title>{% block title %}daniel{% endblock %}</title>
    <!-- 기본 bootstrap -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    {# <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css" /> #}
    <!-- bootstrap: cosmo theme -->
    <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css" /> -->

    <!-- <link rel="stylesheet" href="/static/style.css"/> -->
    <link rel="stylesheet" href="{% static "style.css" %}" />
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">임시#1</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url "root" %}">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact {{ current_datetime }}</a></li>
                    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if not user.is_authenticated %}
                        <li><a href="{% url "accounts:signup" %}">회원가입</a></li>
                        <li><a href="{% url "accounts:login" %}?next={{ request.path }}">로그인</a></li>
                    {% else %}
                        <li><a href="{% url "accounts:profile" %}">프로필</a></li>
                        <li><a href="{% url "accounts:logout" %}?next={{ request.path }}">로그아웃</li>
                    {% endif %}

                    {% comment %} {% if not user.is_authenticated %}
                        <li><a href="/signup/">회원가입</a></li>
                        <li><a href="accounts/login/?next={{ request.path }}">로그인</a></li>
                    {% else %}
                        <li><a href="accouts//profile/">프로필</a></li>
                        <li><a href="/logout/?next={{ request.path }}">로그아웃</a></li>
                    {% endif %} {% endcomment %}
                </ul>
            </div>
        </div>
    </nav>

    {% comment %} <div class="container">
    <div class="alert alert-info">
        alert-info 스타일 메시지
    </div>
    <div class="alert alert-success">
        alert-success 스타일 메시지
    </div>
    <div class="alert alert-warning">
        alert-warning 스타일 메시지
    </div>
    <div class="alert alert-danger">
        alert-danger 스타일 메시지
    </div>
    </div>> {% endcomment %}




    {% if messages %}
        <div class="container">
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                [{{ message.tags }}] {#메시지 level#}
                {{ message.message }} {#실제 메시지 내용#}
            </div>
        {% endfor %}
    {% endif %}


    {% block content %}
    {% endblock %}

    <div id="page-footer">
        <div class="container">
            <p class="text-muted">
                &copy; daniel
                하단 Test
            </p>
        </div>
    </div>
</body>
</html>