tutorial/blog/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv
app_name = 'blog'


urlpatterns = [
    url(r'^$', views_cbv.post_list, name='post_list'),
    url(r'^(?P<pk>\d+)/$', views_cbv.post_detail, name='post_detail'),

    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),

    url(r'^cbv/new/$', views_cbv.post_new),
    url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit),
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete),
    

    # url(r'^$', views.post_list, name='post_list'),
    # url(r'^(?P<id>\d+)/$', views.post_detail, name='post_detail'),
]

tutorial/tutorial/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path

# def root(request):
#     return redirect('blog:post_list')

urlpatterns = [
    # url(r'^$',root, name='root'), 아래 lambda 함수를 써서 하는걸 더 많이 씀 
    url(r'^$', lambda r: redirect('blog:post_list'), name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#settings.MEDIA_URL로 설정을 한다면 document_root=settings.MEDIA_ROOT 에서 파일을 찾아서 서빙을 하겠다
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

tutorial/blog/models.py
import re
from django.conf import settings
from django.urls import reverse
from django.forms import ValidationError
from django.db import models
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import Thumbnail


# Create your models here.

def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')



class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn'),
    )
    #작성자 CharField 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # author = models.CharField(max_length = 20, verbose_name='작성자')  위에 settings AUTH_USER_MODEL을 사용하기떄문에 제거
    # author = models.CharField(max_length = 20, default = 'anonymous') 
    # default = 'anonymous'를 넣어줘도 되긴 하지만 author은 사용자가 직접 넣게 할 것이기 때문에 default는 어울리지 않음

    #길이 제한 이 있는 문자열
    title = models.CharField(max_length=100,verbose_name='제목',help_text='제목을 입력해주세요') 
    # choices = (
    #     ('제목1', '제목1 레이블'),#('저장될 값', 'UI에 보여질 레이블')
    #     ('제목2', '제목2 레이블'),
    #     ('제목3', '제목3 레이블'),
    # ))
    content = models.TextField(verbose_name='내용') #길이 제한이 없는 문자열
    #방법1
    # photo = models.ImageField(blank=True, upload_to='blog/post/%Y/%m/%d'),
    #이미지 파일 user가 이미지를 안올릴루도 있기 때문에 blak=True, upload 위치 설정 처음에 / 쓰면 안됨
    # photo_thumbnail = ImageSpecField(source='photo', processors=[Thumbnail(300,300)],format='JPEG',options={'qulity':60})
    #방법2
    photo = ProcessedImageField(blank=True, upload_to='blog/post/%Y/%m/%d',processors=[Thumbnail(300, 300)],format='JPEG',options={'quality': 60})
    
    tags = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=50,blank=True,
        validators=[lnglat_validator],help_text='경도,위도 포맷으로 입력')
    tag_set = models.ManyToManyField('Tag', blank=True)#다른 APP과 relation을 걸을때는 app이름.Tag로 해주면 됨 
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True) #auto_now_add -> 현재 하나의 Post레코드가 최초 저장
    updated_at = models.DateTimeField(auto_now=True) #해당 레코드가 갱신 될떄마다 자동저장
    
    class Meta:
        ordering = ['-id'] # - 내림차순, default 오름차순
        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE) # 장고 2부터는 Foreignkey 에 대해서 on_delete 지정 해줘야 함 
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)#unique옵션은 같은 테그값이 중복되지 않도록

    def __str__(self):
        return self.name

tutorial/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

tutorial/blog/views.py
from django.contrib import messages
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from .models import Post
from .forms import PostForm

# Create your views here.
def post_list(request):
    print(repr(request.user.is_authenticated))

    qs = Post.objects.all()

    q = request.GET.get('q','')
    if q:
        qs = qs.filter(title__icontains=q)
    # messages.error(request, '에러메시지 테스트')

    response = render(request, 'blog/post_list.html', {
        'post_list': qs,
        'q':q,
    })
    #httpResponse 인스턴스 인데, render를 통해서, 좀더 쉽게 템플릿을 통한 렌더링이 가능
    response
    return response

def post_detail(request, id):
    # try:
    #     post = Post.objects.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404

    post = get_object_or_404(Post, id=id)

    
    return render(request, 'blog/post_detail.html', {
        'post' : post,
    })

def post_new(request):
    if request.method == 'POST': #method 가 POST인지 아닌지 구분 먼저 하고 
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.success(request, '새 포스팅을 저장했습니다.')
            return redirect(post) #post.net_absolute_url() => post_detail
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form': form,
    })
    
def post_edit(request, id):
    post = get_object_or_404(Post, id=id)

    if request.method == 'POST': #method 가 POST인지 아닌지 구분 먼저 하고 
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request, '포스팅을 수정했습니다.')
            return redirect(post) #post.net_absolute_url() => post_detail
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {
        'form': form,
    })
    

tutorial/blog/templates/blog/layout.html
{%extends "layout.html"%} 
<!--project 안에 templates 폴더 안에 있는 layout.html 을 의미 함 -->

{% block title %} Project blog{% endblock %}

tutorial/blog/templates/blog/post_confirm_delete.html
<h1>{{post}} 삭제확인</h1>

정말 삭제하시겠습니까?

<form action="" method="post">
    {% csrf_token %}
    <a href="{{ post.get_absolute_url }}"> 아니요.최소</a>
    <input type="submit" value="예. 삭제하겠습니다. " />
</form>

tutorial/blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% load imagekit %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>{{ post.title }}</h2>

                {%if post.photo%}
                {#<img src="/media/{{post.photo}}" stlye="max-width: 100%;" />#}
                {#<img src="{{post.photo.url}}" stlye="max-width: 100%;" />#}
                {% comment %} 방법1 {% endcomment %}
                {#<img src="{{post.photo_thumbnail.url}}" stlye="max-width: 100%;" />#}
                {% comment %} 방법2 {% endcomment %}
                <img src="{{post.photo.url}}" stlye="max-width: 100%;" />
                    {%thumbnail "100x100" post.photo%}
                    
                    {%thumbnail "100x100" post.photo as thumb%}
                    <img src="{{thumb.url}}" width="{{thumb.width}}" height="{{thumb.height}}"/>

                    {%thumbnail "100x100" post.photo -- stlye="" onclick="" class=""%}
                    
                <!--게시글에 이미지 추가 -->
                {% endif %}
                


                {{ post.content|linebreaks }}

                <hr/>

                <h3>Comments</h3>

                <ul>
                {% for comment in post.comment_set.all %}
                    <li>
                        {{ comment.message }}
                        <small>by {{ comment.author }}</small>
                        <small>at {{ comment.updated_at }}</small>kk
                    </li>
                {% endfor %}
                </ul>

                <hr/>
                <a href="{% url "blog:post_list" %}" class="btn btn-primary">글 목록</a>
                <a href="{% url "blog:post_edit" post.id %}" class="btn btn-primary">수정</a>
            </div>
        </div>
    </div>
{% endblock %}

tutorial/blog/templates/blog/post_form.html
<!-- blog/templates/blog/post_form.html -->
<!--post_form에 enctype 추가 하여 서버로 이미지 전달  -->
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

tutorial/blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Music <sup>by daniel</sup></h1>
            <p>음악</p>
            <p>
                <a class="btn btn-lg btn-primary" href="https://www.facebook.com/hippytokki/">
                        Music 
                    </a>
            </p>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-info">
                    <ul>
                    <li>Beta Test</li>
                    </ul>
                </div>

                <a href="{%url "blog:post_new" %}" class="btn btn-primary pull-right"> New Post</a>

                <p>
                    <form action="" method="get">
                        <input type="text" name="q" value="{{ q }}" />
                        <input type="submit" value="검색" class="btn btn-primary" />
                    </form>
                </p>
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>title</th>
                            <th>author</th>
                            <th>updated_at</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in post_list %}
                            <tr>
                                <td>{{ post.id }}</td>
                                <td><a href="{% url "blog:post_detail" post.id %}">{{ post.title }}</a></td>
                                <td><small>by {{ post.author }}</small></td>
                                <td><small>at {{ post.updated_at }}</small></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>


{% endblock %}